### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [Auriorx/pokemart-auto-redeemer#3] opened 2020-04-17 17:07 UTC
Could you please give instructions how to run and what steps to do, what to install

**Comment by auriorx** [comment] 2020-04-17 17:31
Hi friend,

This package contains the source, but the actual application can be found in the 'releases' section: https://github.com/Auriorx/pokemart-auto-redeemer/releases

As stated in the 'read me':

On the 'release' page I've provided you with versions of the application:

- The 'self-contained' version. This version includes all the external prerequisites in order to run the application (in this case .NET Core 3.1). 

- The 'framework-dependent' version. This is the application only. Upon opening the application you will be prompted to install the prerequisites.

The first option means you should be able to run the application straight away. The second option might require you to install additional software.

Unzip the .zip files and run the .exe file. You might get a security error. This is only because I do not have the funds to "buy" the certificate from Microsoft.

Let me know if this helped you out. :)
~Auriorx

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 17:34
Thank you very much! I installed 7-zip and it extracted!

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 17:36
![image](https://user-images.githubusercontent.com/55881826/79597526-537abd00-80da-11ea-8920-3def48147495.png)
The window is this size...

**Comment by auriorx** [comment] 2020-04-17 17:40
I'm unable to reproduce that issue. Could you answer the following questions:

- Did you install the self-contained or framework-dependent?
- Are you running this on Windows?
- Could you try the other package and see if that one does work?

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 17:40
Windows, Self-contained

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 17:41
I have hi-dpi monitor

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 17:43
I tried frame-work dependant and it still did that... Thanks for your help btw!

**Comment by auriorx** [comment] 2020-04-17 17:58
The releases page now has a new version. Could you download the files and see if your issue is fixed?

On another note, as stated in the read me, to run the application successfully, you would temporarily need to downgrade your monitors resolution to one of the following resolutions:

- 2560x1440
- 1920x1200
- 1920x1080

If you do not do this, the application might click on the wrong buttons. Please be careful with that.

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 18:02
![image](https://user-images.githubusercontent.com/55881826/79599757-f7b23300-80dd-11ea-944e-77ab6550d425.png)
looks a bit squished now

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 18:02
I've tried lowering the resolution with the old release and it didn't work.

**Comment by auriorx** [comment] 2020-04-17 18:05
What's the resolution you are working on? Is it 2736x1824? If you want me to add support for that, I will try my best this weekend.

For now. If you set your resolution to 1920x1080, you can run the application like this and the clicks will align properly.

**Comment by AtomaFajrovulpo** [comment] 2020-04-17 18:08
![image](https://user-images.githubusercontent.com/55881826/79600214-aeaeae80-80de-11ea-9026-38b2f366a546.png)
Works at 1920x1080 even though it is a bit squished! Yes my normal resolution is 2736x1824, if you could add support for it that woudl be great!

**Comment by auriorx** [comment] 2020-04-17 18:09
Great, I'll close this issue and create a new one for the support.

I could not tag you.

New issue:
https://github.com/Auriorx/pokemart-auto-redeemer/issues/4

**Closed as completed by auriorx** 2020-04-17 18:09 UTC
Labels: help wanted
